name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Create PEM file from secret
      run: echo "$PEM_FILE" > /home/ubuntu/devops-backend.pem
      env:
        PEM_FILE: ${{ secrets.PEM_FILE }}

    - name: Ensure correct permissions for PEM file
      run: chmod 400 /home/ubuntu/devops-backend.pem

    - name: SSH to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/devops-backend.pem" ubuntu@ec2-52-91-225-212.compute-1.amazonaws.com << 'EOF'
          sudo docker stop flask-container-frontend || true
          sudo docker rm flask-container-frontend || true
          sudo docker rmi $(sudo docker images -q) || true
          sudo docker pull 316usman/flask-app-frontend:latest
          sudo docker run -d -p 80:80 --name flask-container-frontend 316usman/flask-app-frontend:latest
        EOF
