name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Create PEM file from secret
      run: |
        mkdir -p $RUNNER_TEMP/.ssh
        echo "$PEM_FILE" > $RUNNER_TEMP/.ssh/devops-backend.pem
      env:
        PEM_FILE: ${{ secrets.PEM_FILE }}
        RUNNER_TEMP: ${{ runner.temp }}

    - name: Ensure correct permissions for PEM file
      run: chmod 400 $RUNNER_TEMP/.ssh/devops-backend.pem
      env:
        RUNNER_TEMP: ${{ runner.temp }}

    - name: Debug SSH Connection
      run: |
        ssh -vvv -o StrictHostKeyChecking=no -i $RUNNER_TEMP/.ssh/devops-backend.pem ubuntu@54.198.211.51 << 'EOF'
          echo "SSH Connected"
          sudo docker stop flask-container-frontend || true
          sudo docker rm flask-container-frontend || true
          sudo docker rmi $(sudo docker images -q) || true
          sudo docker pull 316usman/flask-app-frontend:latest
          sudo docker run -d -p 80:80 --name flask-container-frontend 316usman/flask-app-frontend:latest
        EOF
      env:
        RUNNER_TEMP: ${{ runner.temp }}
