name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop Old Container if running
      run: sudo docker stop flask-container-frontend || true
    - name: Delete Old docker container
      run: sudo docker rm flask-container-frontend || true
    - name: Delete Old docker Image
      run: sudo docker rmi $(sudo docker images -q) || true
    - name: Pull Docker image
      run: sudo docker pull 316usman/flask-app-frontend:latest
    - name: Run Docker Container
      run: sudo docker run -d -p 80:80 --name flask-container-frontend 316usman/flask-app-frontend:latest
