name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: SSH to EC2 Instance
      run: |
        ssh -i /home/ubuntu/devops-backend.pem ubuntu@52.91.225.212 << EOF
          sudo docker stop flask-container-frontend || true
          sudo docker rm flask-container-frontend || true
          sudo docker rmi $(sudo docker images -q) || true
          sudo docker pull 316usman/flask-app-frontend:latest
          sudo docker run -d -p 80:80 --name flask-container-frontend 316usman/flask-app-frontend:latest
        EOF
